### ISSUE TITLE
Outdated compinfo

### ISSUE THREAD

**Issue by Cirkutry** [Delta-Icons/android#1011]
The icon for Blinkit isn't applying correctly from the pack, likely due to using outdated component info.

https://iconpusher.com/package/com.grofers.customerapp

![Screenshot_2024-11-03-15-39-59-73_50bdbc0e1f498de16c4c4106a7983ad0.jpg](https://github.com/user-attachments/assets/f9a326cc-cc53-4ae4-8c29-2029fd9be38f)

![Screenshot_2024-11-03-15-39-31-75_50bdbc0e1f498de16c4c4106a7983ad0.jpg](https://github.com/user-attachments/assets/08eda46b-dda0-43e4-a7d9-0d31d08bee5d)

**Comment by GitGitro** [comment]
Thanks for reporting, i'll add it later

**Comment by GitGitro** [comment]
i've just checked and both componentinfo are present, are you using a custom icon from the app?
if not try restarting your launcher and make sure you are on the latest version of Delta

**Comment by Cirkutry** [comment]
You're right. Cleared the cache of the launcher and icon pack seemed to have fixed the issue. Must have gotten bugged cause they did some sort of a force icon push for a special occasion (the icon changed in Google Play too) but now has reverted to the old one.

**Comment by Cirkutry** [comment]
I just noticed https://iconpusher.com/package/com.htetznaing.zfont2 is also not using the icon from the icon pack.

**Comment by wokija** [comment]
I added new ComponentInfos for zFont3. Closing the issue as completed
