### ISSUE TITLE
Memrize icon should depict a rocket ship instead of a bat.

### ISSUE THREAD

**Issue by TraumaD** [Delta-Icons/android#17]
The memrize icon is supposed to be a rocket ship taking off and not a bat. I think that the icon that was made was probably done so around Halloween and so there was a special holiday icon at the time.

current icon:
![memrise](https://user-images.githubusercontent.com/10608836/27208955-8fc8e0d2-520e-11e7-9874-8c712768380e.png)

should be something more like this:
![memrise-purposed](https://user-images.githubusercontent.com/10608836/27208968-9b1909d0-520e-11e7-8124-e4189dd62640.png)

Play Store Link:
https://play.google.com/store/apps/details?id=com.memrise.android.memrisecompanion

**Comment by leifniem** [comment]
Updated it with something close to the stock icon :)
