### ISSUE TITLE
cant seem to build help?

### ISSUE THREAD

**Issue by autoteelar** [Delta-Icons/android#198]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not create task ':app:minifyReleaseWithR8'.
      > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/downstem/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
[downstem@smoke android]$

**Comment by leifniem** [comment]
You are missing the Android SDK in your Systems Environment. Try installing the latest SDK through Android Studios SDK Manager, that should do the trick :)

**Comment by leifniem** [comment]
Closing this due to no feedback.
