### ISSUE TITLE
Stuck on "Checking license ..."

### ISSUE THREAD

**Issue by berkiyo** [Delta-Icons/android#21]
Hi there,

So I recently updated your icon pack to the newest version and whenever I try to open your app, it is stuck on "checking license ...". 

I am running a Sony Xperia SP with LineageOS 14.1 and running no gapps. I am running your icon pack on Nova Launcher however I want to change the icons for specific icons that aren't supported. 

Thanks and keep up the great work!

**Comment by leifniem** [comment]
Hi,

i think that no GApps might be at fault here. Activated the license Check because various sites keep stealing my apk.

Nova might be able to do this anyway. When long pressing on an icon you can choose "Edit" in the icon options and select an icon pack afterwards which leaves you with all the icons there are to manually choose from.

**Comment by berkiyo** [comment]
Unfortunately that isn't the case anymore. Generally your app would load however even when I go to manually choose an icon, it would still prompt the checking license dialog. 

I use the method you mentioned to change my icons however unfortunately I cannot apply any. 

I believe you're right about the gapps issue as there has to be most likely Google Play Services running in the background. In case you were wondering, I downloaded your app through Yalp Store which is a FOSS front-end for the Play Store. 

I understand why you've chosen this route and that's okay 👍 

Thanks for the help anyways.

**Comment by leifniem** [comment]
I see your reason for switching to open source based apps.
You can shoot me a mail to leif.niem@gmail.com and i will send you the APK without a license check or explain to you how you can build it yourself from the source here. Just something i would not wanna make public :)
