### ISSUE TITLE
Can i submit multiple icons for the same app?

### ISSUE THREAD

**Issue by Aninuscsalas** [Delta-Icons/android#251]
How sould i do that?

**Comment by wokija** [comment]
Yes absolutely! Your default icon will be linked inside XML files and applied automatically. Name your alternative(s):
`appname_alt`, `appname_alt_two`, `appname_alt_three`...
Then add line(s) in both drawable.xml files:
`<item name="Appname" drawable="appname" />`
`<item name="Appname Alt" drawable="appname_alt" />`
`<item name="Appname Alt Two" drawable="appname_alt_two" />`
`<item name="Appname Alt Three" drawable="appname_alt_three" />`
