### ISSUE TITLE
Are manufacturer camera and gallery icons not wanted?

### ISSUE THREAD

**Issue by Mertyn** [Delta-Icons/android#260]
I was thinking about making icons for the oneplus camera and gallery app but i noticed that no manufacturer specific camera and gallery icons are in the list right now. Is the idea to keep these apps independent or is there another reason for this?

**Comment by leifniem** [comment]
Feel free. Most of those are just assigned because in the early days i was getting requests for every OEMs apps and did not bother since there were even more back then :P

**Comment by Mertyn** [comment]
Ahh okay thank you :)
