### ISSUE TITLE
Color Pallette 

### ISSUE THREAD

**Issue by iiPlasma** [Delta-Icons/android#35]
Is there anywhere that I could find all the colors used in the icons or like a base-16 made with the core colors of this icon pack? I love this icon pack and plan to donate when I get my first paycheck! Keep doing what you're doing guys!

**Comment by KerstinMaur** [comment]
@iiPlasma, you can have a look at this version of the readme: https://github.com/Delta-Icons/android/blob/c22b23a790b3a7687bd887b2f71a616a37ec03e6/README.md
Does that help? And, thank you so much for your support!  😎

**Comment by iiPlasma** [comment]
Thanks! I'm trying to open it with GIMP, and it isn't working. I'll keep trying at it c:

**Comment by KerstinMaur** [comment]
Is everything fine @iiPlasma?
Have a nice day too! 🌞

**Comment by Steve2955** [comment]
@leifniem I think this issue can be closed
