### ISSUE TITLE
Request: Please Release Version & More Icons

### ISSUE THREAD

**Issue by 0pLuS0** [Delta-Icons/android#38]
Hi,

Your iconset is really nice, but I use custom roms, no gapps, microg, f-droid...

I have been playing around with Yalp Store, but it seems pointless, because most of the apps that are free just like your iconset, if downloaded through Yalp Store, you can't open it, because it just sits doing a license check.

Can you please release this iconset outside of Google Play Store as a free .apk people can download here on GitHub?

Also here are some icon requests;

Simple Calendar
Simple Gallery
microG Settings
Vanilla Music
Yalp Store

Thank you

**Comment by EvangelinePetersen** [comment]
I do not think that Delta will be available as direct .apk file from [https://github.com/Delta-Icons/android/releases](https://github.com/Delta-Icons/android/releases) or on [F-Droid](https://f-droid.org/). And that is totally fine.

**Comment by 0pLuS0** [comment]
Google Play Store is BS, developers tying their apps into their rubbish system! Seriously Google isn't the only means, and then when someone wants to do it another way, and just use a Free App, that is tied to a pay version, you can't use them. That is complete nonsense... The stupid license checks...

Anyhow, this needs to change, Google isn't the only solution and if people will realize how it ties us down, the better off we will be without it...

**Comment by 0pLuS0** [comment]
Developers tying themselves exclusively into Google with FOSS or Proprietary apps isn't good. In the world of computing we have choices, but the way Google has changed Android, Google wants to run the show, and it's locking us in, and it seems as though people aren't seeing this, which is sad.

Maybe people should be aware of the EU's Lawsuit against Google, then you'll realize what I'm saying here...

Anyhow, a developer does have a choice, seems as though developers are just not showing and acknowledging this to the user-base.

**Comment by 0pLuS0** [comment]
Developers tying themselves exclusively into Google with FOSS or Proprietary apps isn't good. In the world of computing we have choices, but the way Google has changed Android, Google wants to run the show, and it's locking us in, and it seems as though people aren't seeing this, which is sad.

Maybe people should be aware of the EU's Lawsuit against Google, then you'll realize what I'm saying here...

Anyhow, a developer does have a choice, seems as though developers are just not showing and acknowledging this to the user-base.

I'm a Geek, hardcore kind too, Unix/Linux all the way, CLI Junkie... The only thing Google is good for is a search engine, other then that, I like nothing Google, can't stand it in my phones and I hack it all out on my Android phones, Xposed, microG, Magisk!

**Comment by leifniem** [comment]
I primarily intended the license check to keep shady sites from distributing Delta in their ecosystem. I think an APK in the releases tab of GitHub would be possible, but first of all i need primarily time to work on it a little. Since i currently lack that requests are closed and the releases have stopped. So please respect my decision in terms of currently not providing new releases or creating new icons.

I added MicroG and Yalp Store to the todo in case that changes, since those additions are reasonable.

**Comment by 0pLuS0** [comment]
@leifniem thanks

**Comment by KerstinMaur** [comment]
Thanks for the info, @leifniem.
Would it be OK if I open another PR next month as part of the @digitalocean [#Hacktoberfest](https://hacktoberfest.digitalocean.com/)?
Of course you can wait with a new release until you have time, may it be this Christmas or next year.  👌
![GIF](https://user-images.githubusercontent.com/32022034/45050534-d247f100-b081-11e8-8174-1944fa7f9956.gif)

**Comment by leifniem** [comment]
@KerstinMaur Sure, feel free, i just hope it'll be before the next Hacktober when i find time to bundle a new release 😅
