### ISSUE TITLE
Noticed a lot of icons have been merged but the app hasn't been updated yet...

### ISSUE THREAD

**Issue by AdamGEmerson** [Delta-Icons/android#44]
Hey Leif,

I know you're a busy guy. Any plans to push an update to the play store soon?

Thanks!

**Comment by KerstinMaur** [comment]
Hi @AdamGEmerson,
unfortunately it will take some time until @leifniem releases a new version on the Play store. 
But he told me that it will be before the next Hacktoberfest (see https://github.com/Delta-Icons/android/issues/38#issuecomment-418473325). 😋
Please feel welcome to open another PR with some icons that you miss. Thanks! 😘

**Comment by wokija** [comment]
I thought the app was no longer maintained. Glad to hear this! During the past months I made a few additional icons I'll be glad to share.

**Comment by leifniem** [comment]
Released it last night, closing this :)
