### ISSUE TITLE
PayMaya is now Maya

### ISSUE THREAD

**Issue by iamflorencejay** [Delta-Icons/android#471]
PayMaya is now Maya, so any plans to update the logo?

**Comment by flameshikari** [comment]
> PayMaya is now Maya, so any plans to update the logo?

Hello, feel free to add a PR with the updated logo.

**Comment by iamflorencejay** [comment]
Sadly, I don't know how to do it, but we'll see

**Comment by flameshikari** [comment]
> Sadly, I don't know how to do it, but we'll see

I'll check that Maya logo, but next time use the in-app icon request tool, not GitHub issues. Check [here](https://github.com/Delta-Icons/android/blob/master/CONTRIBUTING.md) how to contribute icons.

**Comment by wokija** [comment]
For future issues like this (or an existing icon no longer applying automatically), I suggest you send a bugs report through the app so you don't "waste" your icon request.

Thank you!
