### ISSUE TITLE
Mull Icon Out Of Date

### ISSUE THREAD

**Issue by stoponerr** [Delta-Icons/android#484]
No option to request updated icon in app so doing it here instead, mull has changed its icon to a badger and I think it would be cool to make it match the Fennec icon, or at least update it if you find the time.

**Comment by wokija** [comment]
Current beta has it:
![image](https://user-images.githubusercontent.com/14982166/184465095-d6c6bacf-54fa-49eb-9fb9-39122aefcb0b.png)
I was thinking about making it free form (like Fennec) however the vector image has many errors that would need to be corrected first.

Also, you may request icons updates by sending an email to delta.iconpack@gmail.com
