### ISSUE TITLE
CaPod F-Droid Icon support & Discord Icon not working

### ISSUE THREAD

**Issue by SleepDaemon** [Delta-Icons/android#493]
CaPod download from F-Droid repo (i use Droid-ify) does not get applied with Delta Icon even though CaPod icon exists. Also discord icon doesn't get applied, I have reinstalled discord multiple times, reapply the icon pack multiple times yet still does not change the icon.

Device: Samsung S22+
Android Version: 12
Launcher: Default (OneUI 4) [Icon is applied using theme park app [Theme Park](https://galaxystore.samsung.com/detail/com.samsung.android.themedesigner)]

**Comment by SleepDaemon** [comment]
> Are you on the latest [version](https://github.com/Delta-Icons/android/releases/tag/v1.7.1)? If yes could send a bug report here?

yes latest version let me send one

**Comment by SleepDaemon** [comment]
i have send via email
ill send one here now if you meant that send one here

**Comment by SleepDaemon** [comment]
Manufacturer : samsung
Model : SM-S906E
Product : g0qxxx
Screen Resolution : 1080 x 2131 pixels
Android Version : 12
App Version : 1.7.1 R
CandyBar Version : 3.14.2

[reportbugs_31_08_2022_11_59_19.zip](https://github.com/Delta-Icons/android/files/9460169/reportbugs_31_08_2022_11_59_19.zip)

**Comment by SleepDaemon** [comment]
> For CAPod everything is correct and working fine on my end. Same for discord even tho i don't see it in the bug report. Probably has something to do with the launcher, let's see what @wokija says

aight, every other app is fine. Like for simple phone app, i had it downloaded form fdroid but it wouldnt change the icon to delta one. But after the recent update a new version (blue one) came out and it applied to it. So i assumed they made a separate icon for fdroid version.

**Comment by wokija** [comment]
I compared ComponentInfos for CAPod and it's the same so it should apply correctly. I don't see Discord nor Simple Dialer in your bug reports so I can't say for sure but both should also work according to current Delta files. It does seem like it's related to either OneUI or Theme Park app. Can you try a different launcher and see if it solves the issue?

**Comment by SleepDaemon** [comment]
> wait it shouldn't be blue, only if you changed to blue in the phone app settings otherwise should be orange pretty sure it has something to do with the launcher

nope, i have material you theming enabled so i guess it defaults to blue.

**Comment by SleepDaemon** [comment]
> I compared ComponentInfos for CAPod and it's the same so it should apply correctly. I don't see Discord nor Simple Dialer in your bug reports so I can't say for sure but both should also work according to current Delta files. It does seem like it's related to either OneUI or Theme Park app. Can you try a different launcher and see if it solves the issue?

ill check

**Comment by SleepDaemon** [comment]
Ok It turns out, in theme park app unapplying and re-applying the icon doesn't update icons for new apps downloaded. Instead I go create new icon set, select delta, then tap done, and it will collect all app data. Then apply it and boom it's fixed. I guess I have to do this everytime I download a new set of apps.

thanks for the help anyways.
