### ISSUE TITLE
Icon Transparency Issues

### ISSUE THREAD

**Issue by AdamGEmerson** [Delta-Icons/android#50]
Hey Leif, 

I noticed in the most recent update that a few of the icons I contributed seem to be suffering from some issues.  I'll detail them below:

'Adobe XD' - Icon too big. 
'Nascar' - White background has opacity
'Robin Hood Alt' - Has opacity

Is this due to errors in my contribution or could it be a separate issue?  I'm happy to take steps to fix my icons if we can figure out what is causing them to appear different than intended.

For what it's worth, 'Duck Duck Go Alt' and 'Mixer' both look fine.

Thanks!

**Comment by leifniem** [comment]
hi!

good to know, i will fix that right now since i'm merging stuff anyway :) sorry for the hiccup!

**Comment by leifniem** [comment]
The transparency issues were present in your SVG files too, so that must have been an issue on your end, the scaling may have occured because the file had the size of the icon but no padding, which would have caused an upscaling when telling it to export at 192x192 pixels.

All fixed, will be in the update :)

**Comment by AdamGEmerson** [comment]
Awesome!  Thank ya sir.  I plan to contribute some more icons in the near future.  Delta is still my favorite icon set by far.  It seems like more people are starting to chip in and help grow it which is fantastic.

**Comment by AdamGEmerson** [comment]
@leifniem For what it's worth I noticed that the Robinhood Alt icon still has the transparency issue.

**Comment by leifniem** [comment]
Sorry about that, added it to the Todo list for whenever I get to update it

Adam G. Emerson <notifications@github.com> schrieb am Fr., 3. Mai 2019,
20:57:
