### ISSUE TITLE
F-Droid update for v.1.7.2?

### ISSUE THREAD

**Issue by SleepDaemon** [Delta-Icons/android#505]
Saw the new version is out, went to check on Droid-ify (f-droid) to update but didn't show new update for delta app.

**Comment by SleepDaemon** [comment]
yeah, Droid-ify also supports izzydroid repo and many other. But thanks for
letting me know, ill wait.

**Comment by wokija** [comment]
Closing issue as 1.7.2 is now available to download on F-Droid.
