### ISSUE TITLE
How to use Alt icons? 

### ISSUE THREAD

**Issue by SleepDaemon** [Delta-Icons/android#553]
I want to use one of the alt icons for an app, is there a certain method or something I need to do for it to be applied?

**Comment by flameshikari** [comment]
@SleepDaemon just use a suitable launcher (e.g. Nova Launcher) that allows you to manually select an icon for the application from the icon pack

**Comment by SleepDaemon** [comment]
Hi, I discovered the GoodLock Theme park app allows you to change
individual app icons.
