### ISSUE TITLE
[Feature Request] Neo-Launcher support

### ISSUE THREAD

**Issue by Terkyz** [Delta-Icons/android#558]
[Neo-Launcher](https://github.com/NeoApplications/Neo-Launcher) is an excellent open source launcher with many similarities to Lawnchair, and has integrated icon pack support, yet it does not recognize Delta-Icons and trying to set Delta-Icons in Neo-Launcher inside the Delta-Icons app does nothing, [it is literally a black screen](https://i.imgur.com/hQ47LhN.png) with a button that does nothing.

**Comment by wokija** [comment]
It used to works well with Donno's CandyBar contribution to detect Neo. Have you tried applying another icon pack? Does Delta work if you apply it from Neo's settings? I'm thinking Neo Launcher devs changed something that broke the detection.
