### ISSUE TITLE
Undetectable icons

### ISSUE THREAD

**Issue by majsterkovic** [Delta-Icons/android#592]
Some icons are in package but do not work.

**Comment by majsterkovic** [comment]
![Screenshot_2023-02-14-20-36-43-97_50bdbc0e1f498de16c4c4106a7983ad0.jpg](https://user-images.githubusercontent.com/29355048/218843459-941a1550-1b9c-444a-bd34-9c0fb2994471.jpg)

![Screenshot_2023-02-14-20-33-39-41_50bdbc0e1f498de16c4c4106a7983ad0.jpg](https://user-im![Screenshot_2023-02-14-20-35-16-73_50bdbc0e1f498de16c4c4106a7983ad0.jpg](https://user-im![Screenshot_2023-02-14-20-35-59-69_50bdbc0e1f498de16c4c4106a7983ad0.jpg](https://user-images.githubusercontent.com/29355048/218843462-395635c9-5577-432d-9baa-a62395a9c5ca.jpg)

![Uploading Screenshot_2023-02-14-20-35-16-73_50bdbc0e1f498de16c4c4106a7983ad0.jpg …]()

![Uploading Screenshot_2023-02-14-20-35-59-69_50bdbc0e1f498de16c4c4106a7983ad0.jpg …]()

**Comment by majsterkovic** [comment]
- [ ] https://play.google.com/store/apps/details?id=pl.creditagricole.nmobi&hl=pl&gl=US
- [ ] https://play.google.com/store/apps/details?id=pl.wykop.droid&hl=pl&gl=US
- [ ] https://play.google.com/store/apps/details?id=pl.carrefour.carrefourmobile&hl=pl&gl=US
- [ ] https://play.google.com/store/apps/details?id=com.finanteq.finance.bgz&hl=pl&gl=US

**Comment by flameshikari** [comment]
Hello. Please, send a bug report via `Settings — Report Bugs`

**Comment by majsterkovic** [comment]
> Hello. Please, send a bug report via `Settings — Report Bugs`

Why should I report it again? I have pointed out the errors here.

**Comment by flameshikari** [comment]
> Why should I report it again? I have pointed out the errors here.

You didn't include ComponentInfos for these apps here. The bug report will automatically borrow these from your apps (leave your GitHub nickname in the bug report dialog window so I can identify you in a mail box).

Or instead you can use [Icon Pusher](https://play.google.com/store/apps/details?id=dev.southpaw.iconpusher) to share these ComponentInfos to the public database where I can take these.

**Comment by majsterkovic** [comment]
> > Why should I report it again? I have pointed out the errors here.
> 
> You didn't include ComponentInfos for these apps here. The bug report will automatically borrow these from your apps (leave your GitHub nickname in the bug report dialog window so I can identify you in a mail box).
> 
> Or instead you can use [Icon Pusher](https://play.google.com/store/apps/details?id=dev.southpaw.iconpusher) to share these ComponentInfos to the public database where I can take them.

I sent bug report.

**Comment by flameshikari** [comment]
> I sent bug report.

Got it. I'll add missing ComponentInfos in the next beta release.

**Comment by flameshikari** [comment]
f7848d6 fixed
