### ISSUE TITLE
Delta makes Launchers lag.

### ISSUE THREAD

**Issue by Svetov1d** [Delta-Icons/android#594]
While using KISS Launcher and chose Delta icon pack, it makes load Launcher for very long time, same with Xiaomi Launcher.
No lags when using default system icons or any other icon pack.
Xiaomi Redmi Note 9 (merlinnfc)
Firmware: MIUI Global 13.0.3 Android 12
KISS Launcher version: 3.19.0 fdroid

**Comment by tdadvocate** [comment]
Can you provide the devices and firmwares? I have used delta across numerous devices, firmwares, and launchers with no issues. So trying to narrow down any causes besides possibly a device issue.

**Comment by tdadvocate** [comment]
My apologies. I hit the wrong button and couldn't remember how to reopen like a bad github user. Lol. But please provide the device model(s), firmware(s), and launcher version(s) if you could please. I think this issue is likely unrelated to delta but of course you never know.

**Comment by asandikci** [comment]
I have the same problem with delta+KISS 
Delta causes to KISS black screen / freeze or crash
Android version: 8.0.0
Delta version: 1.7.7-beta7.177007 
KISS version: 3.19.0.205
Both Installed from AuroraDroid (F-Droid)

**Comment by flameshikari** [comment]
@Svetov1d @asandikci

[Try this one](https://github.com/flameshikari/delta/suites/11436675223/artifacts/589633496) (install the signed version from the archive). For testing purposes I've removed wrong sized icons. It's not entirely clear why the application crashes, but let's start with this.

**Comment by asandikci** [comment]
### Before process: 
- Remove old Delta version
- Cleared KISS Data from android settings

### Process:
- Downloaded, extracted, and installed signed version (`delta-v2.0.0-foss-signed.apk`)
- Delta > Apply Delta(opens KISS Settings Menu) > User Interface > Icon pack (ADW.Launcher theme) > Select Delta
- After Selecting Delta Icon package, Click home button in navigation bar (⨞ **⭘** 🞎 )
- Screen freezes a few seconds
- Black Screen Occurs
- And after ~a minute android says 
 > _KISS Launcher is not responding,_ 
 > Do you want to close it
 > Close,  Wait

(Or sometimes system automatically kills KISS Launcher and changes default launcher to system launcher)
### Temporary Solution:
- System Settings > Apps > KISS Launcher > Clear Cache
(This Solution is not working after phone restart)

### After Phone Restart:
- Default System Launcher appears a few seconds
- Screen freezes / Black screen few seconds
- KISS Launcher appears, just a loading gif works but neither icons are not loading nor gui is usable
> Note: Surprisingly while i typing these lines (after 4-5 minutes), launcher and icons loaded. Maybe just my phone slow or KISS Launcher is not enough optimize ? But with default system icons restart process done in just ~10 sec

**Comment by flameshikari** [comment]
@asandikci 

Wow, thanks for the detailed report, but... if the custom build didn't help, then I can't help here, sorry.

It's something with KISS Launcher or CandyBar Dashboard (we're using it in Delta). Of course, if you wish, you can open an issue in KISS or CandyBar repo.

**Comment by parsec501** [comment]
It works well with Lawnchair, try that if you want to use the icon pack

**Comment by asandikci** [comment]
I have tried some other icon packs, some of them are working quickly but have few icons. And other icon packs that freezing are have more icons (as in delta icon pack). Probably KISS has a issue or not enough optimized

**Comment by Coehill** [comment]
I am having no performance issues on:
Android version: 13.0.0
Delta version: 1.8.0
KISS version: 3.20.0
Both Installed from AuroraDroid (F-Droid)
