### ISSUE TITLE
Finnish MobilePay has wrong icon

### ISSUE THREAD

**Issue by Arttuej** [Delta-Icons/android#608]
Hello,

Finnish MobilePay has the generic "bank" drawable while it should be:
`<item component="ComponentInfo{fi.danskebank.mobilepay/dk.danskebank.p2p.ui.login.LoginActivity}" drawable="mobile_pay" />`

**Comment by flameshikari** [comment]
Thanks for feedback, I've fixed it in [15acb52](https://github.com/Delta-Icons/android/commit/15acb52b3072c4d53e5a95649444baae85f6cce8)
