### ISSUE TITLE
KISS Launcher Request

### ISSUE THREAD

**Issue by Coehill** [Delta-Icons/android#649]
Would it be possible to add KISS Launcher to the list of supported launchers?

https://f-droid.org/en/packages/fr.neamar.kiss/

**Comment by flameshikari** [comment]
Hello. It's on the list 🤔

As far as I understand, KISS may not work well due to the large number of icons in our icon pack. Maybe it's already fixed, I don't know. (also https://github.com/Delta-Icons/android/issues/594)

![image](https://github.com/Delta-Icons/android/assets/17804422/c3c27f0c-5086-4a3a-b07c-a1f14292a6bb)

**Comment by Coehill** [comment]
Hi @flameshikari, When I tap "Apply Delta", a popup opens that says "KISS Launcher is not installed.  Do you want to open Google Play Store to download and install it?".  However, I already have it installed via FDroid.

**Comment by Coehill** [comment]
I have a workaround:
Open KISS Settings Menu > User Interface > Icon pack (ADW.Launcher theme) > Select Delta

I also turned off "Force icon background" which looked MUCH better.

I am having no performance issues on:
Android version: 13.0.0
Delta version: 1.8.0
KISS version: 3.20.0
Both Installed from AuroraDroid (F-Droid)

**Comment by flameshikari** [comment]
@Coehill I'm not sure there are difference between Google Play and F-Droid versions. I tried both, and both work. (tested on Pixel 5a)

**Comment by flameshikari** [comment]
@Coehill oh, I didn't tried to apply the icon pack via the app. I always set icon packs via launcher settings. :P

**Comment by Donnnno** [comment]
Hi @Coehill this is something that KISS had to implement first. (I've tried to add it to candybar in the past)

There's already an issue open for it:

https://github.com/Neamar/KISS/issues/1936
