### ISSUE TITLE
Some icons not applying correctly

### ISSUE THREAD

**Issue by resiehnnes** [Delta-Icons/android#719]
Shows default icon instead:

DevCheck / flar2.devcheck / https://iconpusher.com/package/flar2.devcheck
AdGuard / com.adguard.android / https://iconpusher.com/package/com.adguard.android
Magic Earth / com.generalmagic.magicearth / https://iconpusher.com/package/com.generalmagic.magicearth

Shows wrong icon:

Calculator / com.simplemobiletools.calculator / https://iconpusher.com/package/com.simplemobiletools.calculator
Calculator / com.sadellie.unitto / https://iconpusher.com/package/com.sadellie.unitto

**Comment by flameshikari** [comment]
Hello!

Would be nice if you provide full ComponentInfo for each listed app (you only provided package names). Or you can push them via [IconPusher](https://play.google.com/store/apps/details?id=dev.southpaw.iconpusher).

**Comment by resiehnnes** [comment]
@flameshikari I updated my first comment with the links provided

**Comment by flameshikari** [comment]
I don't get what you meant by _'shows wrong icon'_. `Unitto` and `Simple Calculator` have icons, and they show correctly. Missing icons added in 15ad1299912af3ef266c9b087f9a0f7ea4236634.

**Comment by resiehnnes** [comment]
@flameshikari so it turned out it was a problem with the launcher app, I did a manual "App list update" in the launcher and now it shows the icons of those two calculator apps correctly.
