### ISSUE TITLE
Potential future Discreet Launcher folder coverage

### ISSUE THREAD

**Issue by TotallyAvailable** [Delta-Icons/android#746]
To slightly increase the chances of making it happen by showing that there's (potential) interest from Users and Creators I'll link it here as well.

- https://github.com/falzonv/discreet-launcher/pull/322

As for potential uses and alternatives there's https://github.com/Donnnno/Arcticons/issues/1859 as well. Obviously doesn't affect you quite as much without delta-adaptive yet, more of a heads-up for potential day 1 coverage.

**Comment by falzonv** [comment]
Hello,

Sorry for the late answer, I confirm there is no limit to the number of apps in a folder, however the text would start to conflict with the base icon after 99 (I considered this case to be rare enough to not handle it).

There are much more details in my reply at https://github.com/Arcticons-Team/Arcticons/issues/1859#issuecomment-1937009427 where I suggest to maybe try to retrieve only the base icon from the icon pack and let Discreet Launcher add the text (number of apps) and set the user-defined color as in the current process, which would avoid having to create dozens of icons just to handle numbers.

Best regards
