### ISSUE TITLE
Please update launcher list

### ISSUE THREAD

**Issue by rafnov** [Delta-Icons/android#890]
When you try to apply Delta there is launcher list displayed.
Some launchers are dead links (Apex, Flick, ZenUI) and some have another annoying dependencies (KISS, Pixel) and some... are really dumb 🤭😂 (Microsoft, Square).

**Comment by GitGitro** [comment]
Hi!
we'll try to make some spring cleaning but as for now the launchers we have set are those.
it's probably better if you make an issue in the [Candybar](https://github.com/zixpo/candybar) repository
