### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Delta-Icons/android#899]
please rebuild from the tagged tree: https://github.com/Delta-Icons/android/releases/tag/v1.9.3

ref: https://monitor.f-droid.org/builds/log/website.leifs.delta.foss/193001#site-footer

**Comment by flameshikari** [comment]
Hello! Thanks for reporting the problem.

I've rebuilt the APK and everything should be fine now.

Also, I found the issue with the GitHub workflow here, I'll fix it before the next release.

**Comment by licaon-kter** [comment]
@flameshikari you've signed with the wrong key? https://monitor.f-droid.org/builds/log/website.leifs.delta.foss/193001#site-footer

**Comment by flameshikari** [comment]
@licaon-kter hm, it's possible as I rebuilt the package in my fork. I've updated secrets and rebuilt the package. Previous and new APK hashes are different now, but I'm still not sure if it's good now.

By the way, how can I get `e072d5b76d4133d85b762633a750871848f41ced3d6d7282339108e9bed15e2e` hash? I mean, is it obtainable from key/keystore/apk, which tool/command I need, etc. Just to make sure if the package is built correctly. I'm a little far from it. Thanks!

**Comment by licaon-kter** [comment]
```
$ apksigner verify --print-certs delta-v1.9.3-foss.apk | head
Signer #1 certificate DN: CN=Leif Niemczik, OU=Selbstständig, O=Leif Niemczik Mediengestaltung, L=Wiesbaden, ST=Hessen, C=DE
Signer #1 certificate SHA-256 digest: e072d5b76d4133d85b762633a750871848f41ced3d6d7282339108e9bed15e2e
Signer #1 certificate SHA-1 digest: b7941293ad33b0f37caab1d6ce6a6cc71ea1bed8
Signer #1 certificate MD5 digest: 50f137ead402086a606369afd40a23a0
```

**Comment by flameshikari** [comment]
Looks like the issue resolved, so closing.
```log
2024-07-13 08:34:05,246 INFO: success: website.leifs.delta.foss
2024-07-13 08:34:05,247 INFO: Finished
2024-07-13 08:34:05,247 INFO: 1 build succeeded
```
