### ISSUE TITLE
palette.svg errors

### ISSUE THREAD

**Issue by marijnnk** [Delta-Icons/android#9]
"Outer space" is mentioned to be #494949 (RGB 73,73,73) but contradicts itself with saying it's rgba(74, 74, 74, 1) (which is #4A4A4A) right below it. The preview color is also 74,74,74. Noticed this while creating a txt of all colors. Pale gold preview color is actually the Peach orange color, while the text below Pale gold is correct, both rgba and hex. If I find more errors, I'll add them to this issue. (Or should I create a new issue?)

NOTE: I used a svg to png converter (http://svgtopng.com/), I haven't noticed any compression issues so far, but I might be wrong. However, it still remains that outer space has at least one error.

![Screenshot](https://user-images.githubusercontent.com/25235249/26950084-c0ca48d2-4c9c-11e7-99fd-7ff40cc76820.png)

**Comment by leifniem** [comment]
It's an svg explicitly to deliver the colors neutral to each computer. Converting it to a png might apply a color profile to the image.

All vector editors should be capable of reading SVG files, so when you're using one there shouldn't be a need to convert before an icon is finished.

I hope i understood your issue correctly, if not feel free to correct me :)

**Comment by marijnnk** [comment]
Although that's true, what my monitor displays doesn't change what's saved in the image. The caption of Outer space says it's Hex color #494949 and rgba(74, 74, 74, 1). Those are not the same colors.

**Comment by leifniem** [comment]
Sorry for letting this one slip, i'll see if i can update the palette somewhen the next days.

**Comment by CodingFrieda** [comment]
Did you find the time to update the palette @leifniem? It's [#Hacktober](https://hacktoberfest.digitalocean.com/) and I am thinking about contributing. 👌

**Comment by leifniem** [comment]
@CodingFrieda @marijnnk New Palette is up, i hope this ones better :)

**Comment by CodingFrieda** [comment]
Thanks @leifniem @marijnnk  😘
