### ISSUE TITLE
New Icon Shape

### ISSUE THREAD

**Issue by yakki-minati** [Delta-Icons/android#973]
This script will make the icons ios shaped, i converted all the icons to ios style but i don't know how to make add them into the apk. I tried uncompressing the original apk file, then replaced icons under /res/ folder then compressed it again but wasn't able to install new apk. Can you show me how can i do that, or can you make an apk for me? This is a python script i asked ChatGPT to create, idk any coding myself.

from PIL import Image, ImageDraw, ImageOps
import os

# Folder paths
input_folder = r"C:\Users\Edwin\Downloads\DeltaIconPack\delta-v1.9.6\res"
output_folder = r"C:\Users\Edwin\Downloads\DeltaIconPack\output"

# Ensure the output folder exists
os.makedirs(output_folder, exist_ok=True)

def get_dominant_color(image):
    # Resize image to reduce the number of colors
    image = image.resize((100, 100))
    colors = image.getcolors(10000)  # Max number of colors to get
    if colors is None:
        return (255, 255, 255)  # Return white if no dominant color found
    dominant_color = max(colors, key=lambda x: x[0])[1]
    return dominant_color

def pastel_color(color):
    # Create a pastel shade by lightening the color
    if isinstance(color, tuple) and len(color) >= 3:
        r, g, b = color[:3]
        return (int(r + (255 - r) * 0.3), int(g + (255 - g) * 0.3), int(b + (255 - b) * 0.3))
    return (255, 255, 255)  # Fallback to white if color is not valid

def process_image(image_path, output_path):
    try:
        with Image.open(image_path) as im:
            # Convert image to RGBA to ensure it has an alpha channel
            im = im.convert("RGBA")

            # Get the dominant color
            dominant = get_dominant_color(im)
            background_color = pastel_color(dominant)

            # Resize the image by 80%
            resized_im = im.resize((int(im.width * 0.8), int(im.height * 0.8)), Image.LANCZOS)

            # Create a new canvas with the pastel background color
            canvas_size = (192, 192)
            canvas = Image.new("RGBA", canvas_size, background_color)

            # Calculate position to center the resized image
            paste_position = (
                (canvas_size[0] - resized_im.width) // 2,
                (canvas_size[1] - resized_im.height) // 2
            )

            # Paste resized image onto the canvas without a mask
            canvas.paste(resized_im, paste_position, resized_im)

            # Create rounded corners mask
            mask = Image.new('L', canvas_size, 0)
            draw = ImageDraw.Draw(mask)
            radius = 30  # Adjust for more or less rounding
            draw.rounded_rectangle([0, 0, canvas_size[0], canvas_size[1]], radius=radius, fill=255)

            # Apply the rounded corners mask
            rounded_image = ImageOps.fit(canvas, canvas_size, centering=(0.5, 0.5))
            rounded_image.putalpha(mask)

            # Save the result
            rounded_image.save(output_path, format="PNG")
            print(f"Successfully processed: {output_path}")

    except Exception as e:
        print(f"Error processing {image_path}: {e}")

# Loop through all images in the folder
for filename in os.listdir(input_folder):
    if filename.lower().endswith(".png"):
        input_image_path = os.path.join(input_folder, filename)
        output_image_path = os.path.join(output_folder, filename)
        process_image(input_image_path, output_image_path)

print("Processing complete!")

**Comment by yakki-minati** [comment]
GitHub's md formatting had made the comments in the script look like headers

**Comment by GitGitro** [comment]
don't uncompress the apk it's optimized at compile time at results difficult to recompile, just clone the repo instead and recompile it with android studio.

for the folders you need to put the pngs inside `android/app/src/main/res/drawable-nodpi`

i'll close this issue as it's not really relevant to the project, if you have issues regarding the icons or the icon pack itself feel free to open a new one!
