### ISSUE TITLE
Make a less washed out version

### ISSUE THREAD

**Issue by RichardLuo0** [Delta-Icons/android#990]
These icons are great and thank you for your hard working! But unfortunately they looks too washed out (too white) and just don't fit other ui elements. I know this might be by design. Could you please make a less washed out version? 
Thank you in advance!

**Comment by wokija** [comment]
Hi, thank you for reaching out! Delta is a pastel-themed icon pack; we follow a strict color palette originally selected by creator Leif. Unfortunately, there is no current plan to branch out and make a second icon pack.

Also, we all wish Android UI would allow to theme all of its elements for a better overall display but it's not the case at this moment.

Hope it answered your question. Closing this issue for now but feel free to communicate with any contributor on discord or email (delta.iconpack@gmail.com)
